project:
  title: "A Quarto D3 Example"
  preview:
    port: 4200
  output-dir: docs
  render: 
    - "*.qmd"
  resources: 
    - img/
    - fonts/
    - js/
    - style/
  
format:
  html:
    theme: style/custom.scss
    df-print: kable

execute: 
  echo: false
  warning: false
  

knitr:
  opts_chunk: 
    dev: jpeg
